[project]
name = "pdm"
version = "0.1.0"
requires-python = "==3.13"
dependencies = []


[[tool.pdm.source]]
name = "jupyterlab_henanigans-index"
url = "https://__token__:${PYPI_ACCESS_TOKEN}@${JUPYTERLAB_HENANIGANS_URL}"
include_packages = ["jupyterlab_henanigans"]
exclude_packages = ["*"]
[tool.pdm]
distribution = false