[project]
name = "jupyterlab_henanigans"
version = "0.2.3"
description = "Henanigans theme for Jupyter Lab."
authors = [
    {name = "Alex Braun", email = "alexander.g.braun@gmail.com"},
]
readme = "README.md"
keywords = [
    "jupyter",
    "jupyter-lab",
    "theme",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Typing :: Typed",
]
requires-python = ">=3.10"
dependencies = [
    "jupyter_server>=1.6",
]

[project.urls]
repository = "https://github.com/theNewFlesh/jupyterlab_henanigans"
documentation = "https://theNewFlesh.github.io/jupyterlab_henanigans"

[tool.pytest.ini_options]
cache_dir = "/home/ubuntu/.pytest_cache"
filterwarnings = [
    # "ignore::UserWarning",
    # "ignore::DeprecationWarning",
    # "ignore::PendingDeprecationWarning",
    "ignore:The --rsyncdir command line argument"
]
markers = [
    "flaky:Flaky test",
]

[tool.coverage.report]
show_missing = true
omit = [
    "*/__init__.py",
    "*/*_test_base.py",
    "*/*_test.py",
    "*/*_tests.py",
    "*/cli.py",
    "*/command.py",
    "*/mock_*.py",
    "*/conftest.py",
]

[tool.mypy]
cache_dir = "/home/ubuntu/.mypy_cache"
python_version = "3.10"
ignore_missing_imports = true
warn_no_return = false
pretty = true
warn_unused_ignores = true

[tool.pdm.dev-dependencies]
lab = []
dev = [
    "build",
    "copier~=7.2",
    "jinja2-time>=0.2.0",
    "jupyter_packaging",
    "jupyterlab-git",
    "jupyterlab>=4.0.0,<5",
    "pip>=24.0",
    "pydantic<2.0.0",
    "rolling-pin>=0.9.5",
]
test = []

[build-system]
requires = ["jupyter_packaging~=0.10,<2", "jupyterlab~=3.0"]
build-backend = "jupyter_packaging.build_api"

[tool.jupyter-packaging.options]
skip-if-exists = ["jupyterlab_henanigans/labextension/static/style.js"]
ensured-targets = ["jupyterlab_henanigans/labextension/static/style.js", "jupyterlab_henanigans/labextension/package.json"]

[tool.jupyter-packaging.builder]
factory = "jupyter_packaging.npm_builder"

[tool.jupyter-packaging.build-args]
build_cmd = "build:prod"
npm = ["jlpm"]

[tool.check-manifest]
ignore = [
    "jupyterlab_henanigans/labextension/**",
    "yarn.lock",
    ".*",
    "package-lock.json"
]
